import React, { useState } from 'react';
import { Loader2 } from 'lucide-react';
import { notifyError, notifyInfo, notifySuccess } from '../utils/toast';

/**
 * Home.jsx
 * - Hero with prompt input (UI-only for Day 1)
 * - Nostalgic styling: gradient, glass-card, mono accents
 * - Responsive and accessible
 */

export default function Home() {
    const [prompt, setPrompt] = useState("");
    const [loading, setLoading ] = useState(false)

    const [generatedVideo, setGeneratedVideo] = useState(null)
    const [example, setExample] = useState("A cat playing piano at sunset")

    const handleGenerate = () =>{
        if(!prompt.trim()){
            notifyError("Please write a prompt first! Using example prompt instead.")
            setPrompt(example)
        } else{
            notifyInfo("Generating your video...");
        }

        setLoading(true);
        setGeneratedVideo(null);

        setTimeout(() => {
            setLoading(false);
            setGeneratedVideo("/demo-video.mp4");
        }, 2000);
    }

    return (
        <section className='max-w-6xl x-auto px-4 py-12  retro-grid text-center'>
            <div className='grid grid-cols-1 lg:grid-cols-2 gap-10 items-center'>
                {/* Left: hero text + prompt card */}
                <div>
                    <h1 className='text-4xl sm:text-5xl font-extrabold nostalgic leading-tight mb-4'>Turn words into short AI videos — with a touch of nostalgia.
                    </h1>
                    <p className='text-slate-300 max-w-xl mb-6'>
                        Type a prompt like{" "}<span className='font-mono text-xs px-2 py-0.5 bg-slate-800/30 rounded'>"A cat playing piano at sunset"</span>{" "} and get a short clip generated by open models. Start small (256px) and scale later.
                    </p>
                    <div className='glass glow-hover rounded-xl p-6 shadow-soft-lg'>
                        <label htmlFor="prompt" className='block text-sm text-slate-200 mb-2'> Your prompt</label>
                        <div className='flex flex-col sm:flex-row gap-3'>
                            <input
                                id='prompt'
                                value={prompt}
                                onChange={(e) => setPrompt(e.target.value)}
                                placeholder={example}
                                className='flex-1 bg-transparent border border-slate-700 rounded-md px-4 py-3 text-slate-100 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500'
                                aria-label="Prompt for video generation"
                            />
                            <button
                                onClick={handleGenerate}
                                className="bg-linear-to-r from-indigo-500 to-violet-500 px-4 py-3 rounded-md text-white font-semibold hover:from-indigo-600 hover:to-violet-600 transition"
                                aria-label="Generate video"
                            >
                                {loading ? (
                                    <>
                                    <Loader2 className='animate-spin' size={20}/>
                                    Generating...
                                    </>
                                ) : (
                                    "Generate"
                                )}
                            </button>
                        </div>
                        <div className="mt-4 text-xs text-slate-400">
                            Tip: keep prompts short and descriptive. You can add style tags like <span className="font-mono">"vhs, cinematic, watercolor"</span>.
                        </div>
                    </div>
                </div>

                {/* Right: visual mock / preview card */}
                <div>
                    <div className="relative glow-hover rounded-xl overflow-hidden glass p-4">
                        <div className="aspect-video bg-linear-to-br from-slate-800/60 to-slate-700/40 rounded-md flex items-center justify-center">
                            {/* placeholder video / mock */}
                            {/* 1️⃣ Loading State */}
                            {loading && (
                                <div className='flex flex-col items-center gap-3'>
                                    <Loader2 className=" animate-spin text-indigo-400" size={36}/>
                                    <p className='text-slate-300 text-sm'> Generating your clip...</p>

                                </div>
                            )}

                            {!loading && generatedVideo && (
                                <video
                                    src={generatedVideo}
                                    autoPlay
                                    loop
                                    muted
                                    className='w-full h-full rounded-md object-cover'
                                />
                            )}
                            
                            {/* 3 Default Placeholder */}
                            {!loading && !generatedVideo && (
                                <div className="text-center">
                                <div className="text-slate-200 font-medium mb-2">Preview</div>
                                <div className="w-48 h-28 rounded-md bg-linear-to-tr from-indigo-700 to-rose-500 opacity-20 flex items-center justify-center text-xs text-slate-100">
                                    <div>
                                        <div className="mb-1">Short clip</div>
                                        <div className="text-[10px] opacity-80">256×256 · 8s</div>
                                    </div>
                                </div>
                            </div>
                            )} 
                            
                        </div>

                        <div className="mt-4 flex items-center justify-between text-sm text-slate-300">
                            <div>FPS: <strong className="text-white">8</strong></div>
                            <div>Resolution: <strong className="text-white">256</strong></div>
                        </div>
                    </div>

                    <div className="mt-4 text-xs text-slate-500">
                        Demo mode: this preview is static on Day 1. We'll connect the real worker next (Colab / HF) and show live progress.
                    </div>
                </div>

            </div>

        </section>
    )

}